"""Add clinic table

Revision ID: 0a04c7cbdb17
Revises: a6dd2570a44e
Create Date: 2025-10-26 15:34:53.942364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0a04c7cbdb17'
down_revision: Union[str, None] = 'a6dd2570a44e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add 'id' column as nullable
    op.add_column('clinics', sa.Column('id', sa.Integer(), nullable=True))
    op.add_column('clinics', sa.Column('clinic_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # Step 2: Fill 'id' with unique values for existing rows
    conn = op.get_bind()
    clinics_table = sa.table('clinics', sa.column('id', sa.Integer()))
    # Use a row_number window function to assign unique ids
    conn.execute(
        sa.text(
            "UPDATE clinics SET id = sub.rn FROM (SELECT ctid, ROW_NUMBER() OVER () AS rn FROM clinics) AS sub WHERE clinics.ctid = sub.ctid"
        )
    )

    # Step 3: Alter 'id' to be NOT NULL and set as primary key
    op.alter_column('clinics', 'id', nullable=False)
    op.create_primary_key('pk_clinics', 'clinics', ['id'])
    op.add_column('clinics', sa.Column('services', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('clinics', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('clinics', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('clinics', sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('clinics', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('clinics', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('clinics', sa.Column('google_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('clinics', sa.Column('phone_combined', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('clinics', sa.Column('email_combined', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('clinics', 'source_country',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.create_index(op.f('ix_clinics_clinic_name'), 'clinics', ['clinic_name'], unique=False)
    op.drop_column('clinics', 'Longitude')
    op.drop_column('clinics', 'Website')
    op.drop_column('clinics', 'Unnamed: 5')
    op.drop_column('clinics', 'Phone')
    op.drop_column('clinics', 'Google Link')
    op.drop_column('clinics', 'Latitude')
    op.drop_column('clinics', 'Location')
    op.drop_column('clinics', 'Unnamed: 4')
    op.drop_column('clinics', 'Phone_Combined')
    op.drop_column('clinics', 'Clinic Name')
    op.drop_column('clinics', 'Services')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinics', sa.Column('Services', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('clinics', sa.Column('Clinic Name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('clinics', sa.Column('Phone_Combined', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('clinics', sa.Column('Unnamed: 4', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('clinics', sa.Column('Location', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('clinics', sa.Column('Latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('clinics', sa.Column('Google Link', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('clinics', sa.Column('Phone', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('clinics', sa.Column('Unnamed: 5', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('clinics', sa.Column('Website', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('clinics', sa.Column('Longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_clinics_clinic_name'), table_name='clinics')
    op.alter_column('clinics', 'source_country',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('clinics', 'email_combined')
    op.drop_column('clinics', 'phone_combined')
    op.drop_column('clinics', 'google_link')
    op.drop_column('clinics', 'longitude')
    op.drop_column('clinics', 'latitude')
    op.drop_column('clinics', 'website')
    op.drop_column('clinics', 'phone')
    op.drop_column('clinics', 'location')
    op.drop_column('clinics', 'services')
    op.drop_column('clinics', 'clinic_name')
    op.drop_column('clinics', 'id')
    # ### end Alembic commands ###
