"""User admin

Revision ID: 28f89b8ac042
Revises: ff0ad2c2908b
Create Date: 2025-08-20 06:32:13.788838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '28f89b8ac042'
down_revision: Union[str, None] = 'ff0ad2c2908b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hospital_referrals')
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_user_is_admin'), 'user', ['is_admin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_is_admin'), table_name='user')
    op.drop_column('user', 'is_admin')
    op.create_table('hospital_referrals',
    sa.Column('Code', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Registration_number', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Keph level', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Facility type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Owner', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Regulatory body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Beds', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Cots', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('County', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Constituency', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Sub county', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Ward', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Operation status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Open_whole_day', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Open_public_holidays', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Open_weekends', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Open_late_night', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Service_names', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Approved', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Public visible', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Closed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_country', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
