"""adding the clincics

Revision ID: d57e9b32607b
Revises: 0a04c7cbdb17
Create Date: 2025-10-26 16:20:55.655640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd57e9b32607b'
down_revision: Union[str, None] = '0a04c7cbdb17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('services', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('google_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone_combined', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email_combined', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinics_clinic_name'), 'clinics', ['clinic_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinics_clinic_name'), table_name='clinics')
    op.drop_table('clinics')
    # ### end Alembic commands ###
