"""Conversation

Revision ID: f73660034055
Revises: 2e5907430723
Create Date: 2025-07-10 16:35:56.432612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f73660034055'
down_revision: Union[str, None] = '2e5907430723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.create_index(op.f('ix_conversations_thread_id'), 'conversations', ['thread_id'], unique=False)
    op.create_index(op.f('ix_conversations_timestamp'), 'conversations', ['timestamp'], unique=False)
    op.create_index(op.f('ix_conversations_title'), 'conversations', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_title'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_timestamp'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_thread_id'), table_name='conversations')
    op.drop_column('conversations', 'title')
    # ### end Alembic commands ###
